### ISSUE TITLE
spaces between lines

### ISSUE THREAD

**Issue by zhukofff** [AAwhittier/MazeGeneratorKotlin#1]
Hello! That's a very interesting project, thx

After compiling I see that I have some spaces between Unicode symbols.

I could not find any issue about this, do you have some assumptions?

What I do:
1. check println() -- it's not the case
2. trying to google 'spaces between Unicode symbols' -- can't find anything

![image](https://user-images.githubusercontent.com/41677260/122538480-44213780-d02f-11eb-82ed-1f9999f74690.png)

**Comment by AAwhittier** [comment]
Hey Daniil, thanks for your interest in the maze gen! This repo is a work in progress and will be updated in the future, for now setting your console line spacing in your editor to 0.8 (or lower until you find a value that works for your editor) will resolve your issue. 

I should have a few hours in the near future to finish writing this one and save the maze to a .png image.

Thanks and good luck!
________________________________
From: Daniil Zhukov ***@***.***>
Sent: Friday, June 18, 2021 3:18:42 AM
To: SirWranwrap/MazeGeneratorKotlin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SirWranwrap/MazeGeneratorKotlin] spaces between lines (#1)


Hello! That's a very interesting project, thx

After compiling I see that I have some spaces between Unicode symbols.

I could not find any issue about this, do you have some assumptions?

What I do:

  1.  check println() -- it's not the case
  2.  trying to google 'spaces between Unicode symbols' -- can't find anything

[image]<https://user-images.githubusercontent.com/41677260/122538480-44213780-d02f-11eb-82ed-1f9999f74690.png>
